### ISSUE TITLE
IRC Nickname Precedence

### ISSUE THREAD

**Issue by cbpowell** [hubot-friends/hubot-irc#6]
Perhaps this is a matter of opinion, but shouldn't the `HUBOT_IRC_NICK` environment variable take precedence over the robot name/alias values?

https://github.com/hubot-friends/hubot-irc/blob/233e986d3f6deb60ef33a22602f39f2f05d3c7bf/index.mjs#L7

I would suggest that should instead be:

```js
nick:  process.env.HUBOT_IRC_NICK ?? robot.name ?? robot.alias ??,
```

That way the IRC Nick can be configured independently of the robot name. Personally I use this to test configuration changes on a 2nd bot instance with a "hubot-test" nickname in IRC.

Happy to submit a PR if folks agree!

**Comment by joeyguerra** [comment]
That's a good point. Do you want to submit a PR for it?

**Comment by cbpowell** [comment]
Just submitted a PR, and did a quick check build and everything seemed OK!

**Comment by joeyguerra** [comment]
Thank you.
